#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgImport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ezFlow_WAFER")]
	public partial class dcFlowDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertDept(Dept instance);
    partial void UpdateDept(Dept instance);
    partial void DeleteDept(Dept instance);
    partial void InsertDeptLevel(DeptLevel instance);
    partial void UpdateDeptLevel(DeptLevel instance);
    partial void DeleteDeptLevel(DeptLevel instance);
    partial void InsertEmp(Emp instance);
    partial void UpdateEmp(Emp instance);
    partial void DeleteEmp(Emp instance);
    partial void InsertEmpBak(EmpBak instance);
    partial void UpdateEmpBak(EmpBak instance);
    partial void DeleteEmpBak(EmpBak instance);
    partial void InsertPos(Pos instance);
    partial void UpdatePos(Pos instance);
    partial void DeletePos(Pos instance);
    partial void InsertPosLevel(PosLevel instance);
    partial void UpdatePosLevel(PosLevel instance);
    partial void DeletePosLevel(PosLevel instance);
    partial void InsertRole(Role instance);
    partial void UpdateRole(Role instance);
    partial void DeleteRole(Role instance);
    partial void InsertOrgImport(OrgImport instance);
    partial void UpdateOrgImport(OrgImport instance);
    partial void DeleteOrgImport(OrgImport instance);
    partial void InsertSysVar(SysVar instance);
    partial void UpdateSysVar(SysVar instance);
    partial void DeleteSysVar(SysVar instance);
    #endregion
		
		public dcFlowDataContext() : 
				base(global::OrgImport.Properties.Settings.Default.FlowConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcFlowDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcFlowDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcFlowDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcFlowDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dept> Dept
		{
			get
			{
				return this.GetTable<Dept>();
			}
		}
		
		public System.Data.Linq.Table<DeptLevel> DeptLevel
		{
			get
			{
				return this.GetTable<DeptLevel>();
			}
		}
		
		public System.Data.Linq.Table<Emp> Emp
		{
			get
			{
				return this.GetTable<Emp>();
			}
		}
		
		public System.Data.Linq.Table<EmpBak> EmpBak
		{
			get
			{
				return this.GetTable<EmpBak>();
			}
		}
		
		public System.Data.Linq.Table<Pos> Pos
		{
			get
			{
				return this.GetTable<Pos>();
			}
		}
		
		public System.Data.Linq.Table<PosLevel> PosLevel
		{
			get
			{
				return this.GetTable<PosLevel>();
			}
		}
		
		public System.Data.Linq.Table<Role> Role
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<OrgImport> OrgImport
		{
			get
			{
				return this.GetTable<OrgImport>();
			}
		}
		
		public System.Data.Linq.Table<SysVar> SysVar
		{
			get
			{
				return this.GetTable<SysVar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dept")]
	public partial class Dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _idParent;
		
		private string _name;
		
		private string _path;
		
		private string _DeptLevel_id;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidParentChanging(string value);
    partial void OnidParentChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpathChanging(string value);
    partial void OnpathChanged();
    partial void OnDeptLevel_idChanging(string value);
    partial void OnDeptLevel_idChanged();
    #endregion
		
		public Dept()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idParent", DbType="NVarChar(50)")]
		public string idParent
		{
			get
			{
				return this._idParent;
			}
			set
			{
				if ((this._idParent != value))
				{
					this.OnidParentChanging(value);
					this.SendPropertyChanging();
					this._idParent = value;
					this.SendPropertyChanged("idParent");
					this.OnidParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_path", DbType="NVarChar(2000)")]
		public string path
		{
			get
			{
				return this._path;
			}
			set
			{
				if ((this._path != value))
				{
					this.OnpathChanging(value);
					this.SendPropertyChanging();
					this._path = value;
					this.SendPropertyChanged("path");
					this.OnpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptLevel_id", DbType="NVarChar(50)")]
		public string DeptLevel_id
		{
			get
			{
				return this._DeptLevel_id;
			}
			set
			{
				if ((this._DeptLevel_id != value))
				{
					this.OnDeptLevel_idChanging(value);
					this.SendPropertyChanging();
					this._DeptLevel_id = value;
					this.SendPropertyChanged("DeptLevel_id");
					this.OnDeptLevel_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeptLevel")]
	public partial class DeptLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private System.Nullable<decimal> _sorting;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsortingChanging(System.Nullable<decimal> value);
    partial void OnsortingChanged();
    #endregion
		
		public DeptLevel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sorting", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> sorting
		{
			get
			{
				return this._sorting;
			}
			set
			{
				if ((this._sorting != value))
				{
					this.OnsortingChanging(value);
					this.SendPropertyChanging();
					this._sorting = value;
					this.SendPropertyChanged("sorting");
					this.OnsortingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emp")]
	public partial class Emp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _pw;
		
		private string _name;
		
		private System.Nullable<bool> _isNeedAgent;
		
		private System.Nullable<System.DateTime> _dateB;
		
		private System.Nullable<System.DateTime> _dateE;
		
		private string _email;
		
		private string _login;
		
		private string _sex;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnpwChanging(string value);
    partial void OnpwChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnisNeedAgentChanging(System.Nullable<bool> value);
    partial void OnisNeedAgentChanged();
    partial void OndateBChanging(System.Nullable<System.DateTime> value);
    partial void OndateBChanged();
    partial void OndateEChanging(System.Nullable<System.DateTime> value);
    partial void OndateEChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    #endregion
		
		public Emp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pw", DbType="NVarChar(50)")]
		public string pw
		{
			get
			{
				return this._pw;
			}
			set
			{
				if ((this._pw != value))
				{
					this.OnpwChanging(value);
					this.SendPropertyChanging();
					this._pw = value;
					this.SendPropertyChanged("pw");
					this.OnpwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isNeedAgent", DbType="Bit")]
		public System.Nullable<bool> isNeedAgent
		{
			get
			{
				return this._isNeedAgent;
			}
			set
			{
				if ((this._isNeedAgent != value))
				{
					this.OnisNeedAgentChanging(value);
					this.SendPropertyChanging();
					this._isNeedAgent = value;
					this.SendPropertyChanged("isNeedAgent");
					this.OnisNeedAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateB", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateB
		{
			get
			{
				return this._dateB;
			}
			set
			{
				if ((this._dateB != value))
				{
					this.OndateBChanging(value);
					this.SendPropertyChanging();
					this._dateB = value;
					this.SendPropertyChanged("dateB");
					this.OndateBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateE", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateE
		{
			get
			{
				return this._dateE;
			}
			set
			{
				if ((this._dateE != value))
				{
					this.OndateEChanging(value);
					this.SendPropertyChanging();
					this._dateE = value;
					this.SendPropertyChanged("dateE");
					this.OndateEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(50)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(50)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmpBak")]
	public partial class EmpBak : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _pw;
		
		private string _name;
		
		private System.Nullable<bool> _isNeedAgent;
		
		private System.Nullable<System.DateTime> _dateB;
		
		private System.Nullable<System.DateTime> _dateE;
		
		private string _email;
		
		private string _login;
		
		private string _sex;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnpwChanging(string value);
    partial void OnpwChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnisNeedAgentChanging(System.Nullable<bool> value);
    partial void OnisNeedAgentChanged();
    partial void OndateBChanging(System.Nullable<System.DateTime> value);
    partial void OndateBChanged();
    partial void OndateEChanging(System.Nullable<System.DateTime> value);
    partial void OndateEChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    #endregion
		
		public EmpBak()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pw", DbType="NVarChar(50)")]
		public string pw
		{
			get
			{
				return this._pw;
			}
			set
			{
				if ((this._pw != value))
				{
					this.OnpwChanging(value);
					this.SendPropertyChanging();
					this._pw = value;
					this.SendPropertyChanged("pw");
					this.OnpwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isNeedAgent", DbType="Bit")]
		public System.Nullable<bool> isNeedAgent
		{
			get
			{
				return this._isNeedAgent;
			}
			set
			{
				if ((this._isNeedAgent != value))
				{
					this.OnisNeedAgentChanging(value);
					this.SendPropertyChanging();
					this._isNeedAgent = value;
					this.SendPropertyChanged("isNeedAgent");
					this.OnisNeedAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateB", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateB
		{
			get
			{
				return this._dateB;
			}
			set
			{
				if ((this._dateB != value))
				{
					this.OndateBChanging(value);
					this.SendPropertyChanging();
					this._dateB = value;
					this.SendPropertyChanged("dateB");
					this.OndateBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateE", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateE
		{
			get
			{
				return this._dateE;
			}
			set
			{
				if ((this._dateE != value))
				{
					this.OndateEChanging(value);
					this.SendPropertyChanging();
					this._dateE = value;
					this.SendPropertyChanged("dateE");
					this.OndateEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(50)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="NVarChar(50)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pos")]
	public partial class Pos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private string _PosLevel_id;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnPosLevel_idChanging(string value);
    partial void OnPosLevel_idChanged();
    #endregion
		
		public Pos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosLevel_id", DbType="NVarChar(50)")]
		public string PosLevel_id
		{
			get
			{
				return this._PosLevel_id;
			}
			set
			{
				if ((this._PosLevel_id != value))
				{
					this.OnPosLevel_idChanging(value);
					this.SendPropertyChanging();
					this._PosLevel_id = value;
					this.SendPropertyChanged("PosLevel_id");
					this.OnPosLevel_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PosLevel")]
	public partial class PosLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _name;
		
		private System.Nullable<int> _sorting;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsortingChanging(System.Nullable<int> value);
    partial void OnsortingChanged();
    #endregion
		
		public PosLevel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sorting", DbType="Int")]
		public System.Nullable<int> sorting
		{
			get
			{
				return this._sorting;
			}
			set
			{
				if ((this._sorting != value))
				{
					this.OnsortingChanging(value);
					this.SendPropertyChanging();
					this._sorting = value;
					this.SendPropertyChanged("sorting");
					this.OnsortingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Role")]
	public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _auto;
		
		private string _id;
		
		private string _idParent;
		
		private string _Dept_id;
		
		private string _Pos_id;
		
		private System.Nullable<System.DateTime> _dateB;
		
		private System.Nullable<System.DateTime> _dateE;
		
		private string _Emp_id;
		
		private System.Nullable<bool> _mgDefault;
		
		private System.Nullable<bool> _deptMg;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnautoChanging(int value);
    partial void OnautoChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnidParentChanging(string value);
    partial void OnidParentChanged();
    partial void OnDept_idChanging(string value);
    partial void OnDept_idChanged();
    partial void OnPos_idChanging(string value);
    partial void OnPos_idChanged();
    partial void OndateBChanging(System.Nullable<System.DateTime> value);
    partial void OndateBChanged();
    partial void OndateEChanging(System.Nullable<System.DateTime> value);
    partial void OndateEChanged();
    partial void OnEmp_idChanging(string value);
    partial void OnEmp_idChanged();
    partial void OnmgDefaultChanging(System.Nullable<bool> value);
    partial void OnmgDefaultChanged();
    partial void OndeptMgChanging(System.Nullable<bool> value);
    partial void OndeptMgChanged();
    #endregion
		
		public Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int auto
		{
			get
			{
				return this._auto;
			}
			set
			{
				if ((this._auto != value))
				{
					this.OnautoChanging(value);
					this.SendPropertyChanging();
					this._auto = value;
					this.SendPropertyChanged("auto");
					this.OnautoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(100)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idParent", DbType="NVarChar(100)")]
		public string idParent
		{
			get
			{
				return this._idParent;
			}
			set
			{
				if ((this._idParent != value))
				{
					this.OnidParentChanging(value);
					this.SendPropertyChanging();
					this._idParent = value;
					this.SendPropertyChanged("idParent");
					this.OnidParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_id", DbType="NVarChar(50)")]
		public string Dept_id
		{
			get
			{
				return this._Dept_id;
			}
			set
			{
				if ((this._Dept_id != value))
				{
					this.OnDept_idChanging(value);
					this.SendPropertyChanging();
					this._Dept_id = value;
					this.SendPropertyChanged("Dept_id");
					this.OnDept_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos_id", DbType="NVarChar(50)")]
		public string Pos_id
		{
			get
			{
				return this._Pos_id;
			}
			set
			{
				if ((this._Pos_id != value))
				{
					this.OnPos_idChanging(value);
					this.SendPropertyChanging();
					this._Pos_id = value;
					this.SendPropertyChanged("Pos_id");
					this.OnPos_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateB", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateB
		{
			get
			{
				return this._dateB;
			}
			set
			{
				if ((this._dateB != value))
				{
					this.OndateBChanging(value);
					this.SendPropertyChanging();
					this._dateB = value;
					this.SendPropertyChanged("dateB");
					this.OndateBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateE", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateE
		{
			get
			{
				return this._dateE;
			}
			set
			{
				if ((this._dateE != value))
				{
					this.OndateEChanging(value);
					this.SendPropertyChanging();
					this._dateE = value;
					this.SendPropertyChanged("dateE");
					this.OndateEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_id", DbType="NVarChar(50)")]
		public string Emp_id
		{
			get
			{
				return this._Emp_id;
			}
			set
			{
				if ((this._Emp_id != value))
				{
					this.OnEmp_idChanging(value);
					this.SendPropertyChanging();
					this._Emp_id = value;
					this.SendPropertyChanged("Emp_id");
					this.OnEmp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgDefault", DbType="Bit")]
		public System.Nullable<bool> mgDefault
		{
			get
			{
				return this._mgDefault;
			}
			set
			{
				if ((this._mgDefault != value))
				{
					this.OnmgDefaultChanging(value);
					this.SendPropertyChanging();
					this._mgDefault = value;
					this.SendPropertyChanged("mgDefault");
					this.OnmgDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deptMg", DbType="Bit")]
		public System.Nullable<bool> deptMg
		{
			get
			{
				return this._deptMg;
			}
			set
			{
				if ((this._deptMg != value))
				{
					this.OndeptMgChanging(value);
					this.SendPropertyChanging();
					this._deptMg = value;
					this.SendPropertyChanged("deptMg");
					this.OndeptMgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrgImport")]
	public partial class OrgImport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iAutoKey;
		
		private System.Nullable<bool> _bSyncLoginID;
		
		private string _sFrontLoginID;
		
		private System.Nullable<bool> _bFullImport;
		
		private string _sDeptTopCode;
		
		private System.Nullable<bool> _bRoleTopEmpty;
		
		private System.Nullable<bool> _bSyncLoginPW;
		
		private System.Nullable<bool> _bLevel;
		
		private System.Nullable<bool> _bTest;
		
		private string _sTestMail;
		
		private System.Nullable<bool> _bFixBug;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniAutoKeyChanging(int value);
    partial void OniAutoKeyChanged();
    partial void OnbSyncLoginIDChanging(System.Nullable<bool> value);
    partial void OnbSyncLoginIDChanged();
    partial void OnsFrontLoginIDChanging(string value);
    partial void OnsFrontLoginIDChanged();
    partial void OnbFullImportChanging(System.Nullable<bool> value);
    partial void OnbFullImportChanged();
    partial void OnsDeptTopCodeChanging(string value);
    partial void OnsDeptTopCodeChanged();
    partial void OnbRoleTopEmptyChanging(System.Nullable<bool> value);
    partial void OnbRoleTopEmptyChanged();
    partial void OnbSyncLoginPWChanging(System.Nullable<bool> value);
    partial void OnbSyncLoginPWChanged();
    partial void OnbLevelChanging(System.Nullable<bool> value);
    partial void OnbLevelChanged();
    partial void OnbTestChanging(System.Nullable<bool> value);
    partial void OnbTestChanged();
    partial void OnsTestMailChanging(string value);
    partial void OnsTestMailChanged();
    partial void OnbFixBugChanging(System.Nullable<bool> value);
    partial void OnbFixBugChanged();
    #endregion
		
		public OrgImport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iAutoKey", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iAutoKey
		{
			get
			{
				return this._iAutoKey;
			}
			set
			{
				if ((this._iAutoKey != value))
				{
					this.OniAutoKeyChanging(value);
					this.SendPropertyChanging();
					this._iAutoKey = value;
					this.SendPropertyChanged("iAutoKey");
					this.OniAutoKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bSyncLoginID", DbType="Bit")]
		public System.Nullable<bool> bSyncLoginID
		{
			get
			{
				return this._bSyncLoginID;
			}
			set
			{
				if ((this._bSyncLoginID != value))
				{
					this.OnbSyncLoginIDChanging(value);
					this.SendPropertyChanging();
					this._bSyncLoginID = value;
					this.SendPropertyChanged("bSyncLoginID");
					this.OnbSyncLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sFrontLoginID", DbType="NVarChar(50)")]
		public string sFrontLoginID
		{
			get
			{
				return this._sFrontLoginID;
			}
			set
			{
				if ((this._sFrontLoginID != value))
				{
					this.OnsFrontLoginIDChanging(value);
					this.SendPropertyChanging();
					this._sFrontLoginID = value;
					this.SendPropertyChanged("sFrontLoginID");
					this.OnsFrontLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bFullImport", DbType="Bit")]
		public System.Nullable<bool> bFullImport
		{
			get
			{
				return this._bFullImport;
			}
			set
			{
				if ((this._bFullImport != value))
				{
					this.OnbFullImportChanging(value);
					this.SendPropertyChanging();
					this._bFullImport = value;
					this.SendPropertyChanged("bFullImport");
					this.OnbFullImportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDeptTopCode", DbType="NVarChar(50)")]
		public string sDeptTopCode
		{
			get
			{
				return this._sDeptTopCode;
			}
			set
			{
				if ((this._sDeptTopCode != value))
				{
					this.OnsDeptTopCodeChanging(value);
					this.SendPropertyChanging();
					this._sDeptTopCode = value;
					this.SendPropertyChanged("sDeptTopCode");
					this.OnsDeptTopCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bRoleTopEmpty", DbType="Bit")]
		public System.Nullable<bool> bRoleTopEmpty
		{
			get
			{
				return this._bRoleTopEmpty;
			}
			set
			{
				if ((this._bRoleTopEmpty != value))
				{
					this.OnbRoleTopEmptyChanging(value);
					this.SendPropertyChanging();
					this._bRoleTopEmpty = value;
					this.SendPropertyChanged("bRoleTopEmpty");
					this.OnbRoleTopEmptyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bSyncLoginPW", DbType="Bit")]
		public System.Nullable<bool> bSyncLoginPW
		{
			get
			{
				return this._bSyncLoginPW;
			}
			set
			{
				if ((this._bSyncLoginPW != value))
				{
					this.OnbSyncLoginPWChanging(value);
					this.SendPropertyChanging();
					this._bSyncLoginPW = value;
					this.SendPropertyChanged("bSyncLoginPW");
					this.OnbSyncLoginPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bLevel", DbType="Bit")]
		public System.Nullable<bool> bLevel
		{
			get
			{
				return this._bLevel;
			}
			set
			{
				if ((this._bLevel != value))
				{
					this.OnbLevelChanging(value);
					this.SendPropertyChanging();
					this._bLevel = value;
					this.SendPropertyChanged("bLevel");
					this.OnbLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bTest", DbType="Bit")]
		public System.Nullable<bool> bTest
		{
			get
			{
				return this._bTest;
			}
			set
			{
				if ((this._bTest != value))
				{
					this.OnbTestChanging(value);
					this.SendPropertyChanging();
					this._bTest = value;
					this.SendPropertyChanged("bTest");
					this.OnbTestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTestMail", DbType="NVarChar(200)")]
		public string sTestMail
		{
			get
			{
				return this._sTestMail;
			}
			set
			{
				if ((this._sTestMail != value))
				{
					this.OnsTestMailChanging(value);
					this.SendPropertyChanging();
					this._sTestMail = value;
					this.SendPropertyChanged("sTestMail");
					this.OnsTestMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bFixBug", DbType="Bit")]
		public System.Nullable<bool> bFixBug
		{
			get
			{
				return this._bFixBug;
			}
			set
			{
				if ((this._bFixBug != value))
				{
					this.OnbFixBugChanging(value);
					this.SendPropertyChanging();
					this._bFixBug = value;
					this.SendPropertyChanged("bFixBug");
					this.OnbFixBugChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SysVar")]
	public partial class SysVar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _urlRoot;
		
		private string _mailServer;
		
		private string _mailID;
		
		private string _mailPW;
		
		private string _senderMail;
		
		private string _senderName;
		
		private System.Nullable<int> _maxKey;
		
		private string _webSrvURL;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnurlRootChanging(string value);
    partial void OnurlRootChanged();
    partial void OnmailServerChanging(string value);
    partial void OnmailServerChanged();
    partial void OnmailIDChanging(string value);
    partial void OnmailIDChanged();
    partial void OnmailPWChanging(string value);
    partial void OnmailPWChanged();
    partial void OnsenderMailChanging(string value);
    partial void OnsenderMailChanged();
    partial void OnsenderNameChanging(string value);
    partial void OnsenderNameChanged();
    partial void OnmaxKeyChanging(System.Nullable<int> value);
    partial void OnmaxKeyChanged();
    partial void OnwebSrvURLChanging(string value);
    partial void OnwebSrvURLChanged();
    #endregion
		
		public SysVar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlRoot", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string urlRoot
		{
			get
			{
				return this._urlRoot;
			}
			set
			{
				if ((this._urlRoot != value))
				{
					this.OnurlRootChanging(value);
					this.SendPropertyChanging();
					this._urlRoot = value;
					this.SendPropertyChanged("urlRoot");
					this.OnurlRootChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailServer", DbType="NVarChar(50)")]
		public string mailServer
		{
			get
			{
				return this._mailServer;
			}
			set
			{
				if ((this._mailServer != value))
				{
					this.OnmailServerChanging(value);
					this.SendPropertyChanging();
					this._mailServer = value;
					this.SendPropertyChanged("mailServer");
					this.OnmailServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailID", DbType="NVarChar(50)")]
		public string mailID
		{
			get
			{
				return this._mailID;
			}
			set
			{
				if ((this._mailID != value))
				{
					this.OnmailIDChanging(value);
					this.SendPropertyChanging();
					this._mailID = value;
					this.SendPropertyChanged("mailID");
					this.OnmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailPW", DbType="NVarChar(50)")]
		public string mailPW
		{
			get
			{
				return this._mailPW;
			}
			set
			{
				if ((this._mailPW != value))
				{
					this.OnmailPWChanging(value);
					this.SendPropertyChanging();
					this._mailPW = value;
					this.SendPropertyChanged("mailPW");
					this.OnmailPWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderMail", DbType="NVarChar(50)")]
		public string senderMail
		{
			get
			{
				return this._senderMail;
			}
			set
			{
				if ((this._senderMail != value))
				{
					this.OnsenderMailChanging(value);
					this.SendPropertyChanging();
					this._senderMail = value;
					this.SendPropertyChanged("senderMail");
					this.OnsenderMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderName", DbType="NVarChar(50)")]
		public string senderName
		{
			get
			{
				return this._senderName;
			}
			set
			{
				if ((this._senderName != value))
				{
					this.OnsenderNameChanging(value);
					this.SendPropertyChanging();
					this._senderName = value;
					this.SendPropertyChanged("senderName");
					this.OnsenderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxKey", DbType="Int")]
		public System.Nullable<int> maxKey
		{
			get
			{
				return this._maxKey;
			}
			set
			{
				if ((this._maxKey != value))
				{
					this.OnmaxKeyChanging(value);
					this.SendPropertyChanging();
					this._maxKey = value;
					this.SendPropertyChanged("maxKey");
					this.OnmaxKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_webSrvURL", DbType="NVarChar(50)")]
		public string webSrvURL
		{
			get
			{
				return this._webSrvURL;
			}
			set
			{
				if ((this._webSrvURL != value))
				{
					this.OnwebSrvURLChanging(value);
					this.SendPropertyChanging();
					this._webSrvURL = value;
					this.SendPropertyChanged("webSrvURL");
					this.OnwebSrvURLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
