#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgImport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WAFERHR")]
	public partial class dcHrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    #endregion
		
		public dcHrDataContext() : 
				base(global::OrgImport.Properties.Settings.Default.HRConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BASE> BASE
		{
			get
			{
				return this.GetTable<BASE>();
			}
		}
		
		public System.Data.Linq.Table<BASETTS> BASETTS
		{
			get
			{
				return this.GetTable<BASETTS>();
			}
		}
		
		public System.Data.Linq.Table<DEPTA> DEPTA
		{
			get
			{
				return this.GetTable<DEPTA>();
			}
		}
		
		public System.Data.Linq.Table<DEPT> DEPT
		{
			get
			{
				return this.GetTable<DEPT>();
			}
		}
		
		public System.Data.Linq.Table<JOB> JOB
		{
			get
			{
				return this.GetTable<JOB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASE")]
	public partial class BASE
	{
		
		private string _NOBR;
		
		private string _NAME_C;
		
		private string _NAME_E;
		
		private string _NAME_P;
		
		private System.Nullable<char> _SEX;
		
		private System.Nullable<System.DateTime> _BIRDT;
		
		private string _ADDR1;
		
		private string _ADDR2;
		
		private string _TEL1;
		
		private string _TEL2;
		
		private string _BBCALL;
		
		private string _EMAIL;
		
		private string _GSM;
		
		private string _IDNO;
		
		private string _CONT_MAN;
		
		private string _CONT_TEL;
		
		private string _CONT_GSM;
		
		private string _CONT_MAN2;
		
		private string _CONT_TEL2;
		
		private string _CONT_GSM2;
		
		private string _BLOOD;
		
		private string _PASSWORD;
		
		private string _POSTCODE1;
		
		private string _POSTCODE2;
		
		private System.Nullable<char> _BANK_CODE;
		
		private string _BANKNO;
		
		private string _ACCOUNT_NO;
		
		private string _ACCOUNT_NA;
		
		private string _MARRY;
		
		private string _COUNTRY;
		
		private bool _COUNT_MA;
		
		private string _ARMY;
		
		private string _PRO_MAN1;
		
		private string _PRO_ADDR1;
		
		private string _PRO_ID1;
		
		private string _PRO_TEL1;
		
		private string _PRO_MAN2;
		
		private string _PRO_ADDR2;
		
		private string _PRO_ID2;
		
		private string _PRO_TEL2;
		
		private string _ARMY_TYPE;
		
		private string _N_NOBR;
		
		private string _NOBR_B;
		
		private string _PROVINCE;
		
		private string _BORN_ADDR;
		
		private System.Nullable<decimal> _TAXCNT;
		
		private string _KEY_MAN;
		
		private System.Nullable<System.DateTime> _KEY_DATE;
		
		private System.Nullable<char> _ID_TYPE;
		
		private string _TAXNO;
		
		private System.Nullable<decimal> _PRETAX;
		
		private string _PHOTO;
		
		private System.Nullable<char> _CONT_REL1;
		
		private System.Nullable<char> _CONT_REL2;
		
		private string _ACCOUNT_MA;
		
		private string _MATNO;
		
		private string _SUBTEL;
		
		private string _LA_NO;
		
		private System.Nullable<System.DateTime> _LA_ADATE;
		
		private string _LA_RECRUIT;
		
		private string _LA_RECURRE;
		
		private string _LA_TYPE;
		
		private System.Nullable<System.DateTime> _LA_LDATE;
		
		private System.Nullable<System.DateTime> _LA_EDATE;
		
		private System.Nullable<bool> _LA_CYCLE;
		
		private string _LA_NOTE;
		
		private System.Nullable<decimal> _LA_AMT;
		
		private System.Nullable<System.DateTime> _LA_OUTDATE;
		
		private string _FiveYears;
		
		private string _FiveRecipient;
		
		private string _TenYears;
		
		private string _TenRecipient;
		
		private string _FifteenYears;
		
		private string _FiteenRecipient;
		
		public BASE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this._NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_C", DbType="Char(10)")]
		public string NAME_C
		{
			get
			{
				return this._NAME_C;
			}
			set
			{
				if ((this._NAME_C != value))
				{
					this._NAME_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_E", DbType="Char(50)")]
		public string NAME_E
		{
			get
			{
				return this._NAME_E;
			}
			set
			{
				if ((this._NAME_E != value))
				{
					this._NAME_E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_P", DbType="Char(50)")]
		public string NAME_P
		{
			get
			{
				return this._NAME_P;
			}
			set
			{
				if ((this._NAME_P != value))
				{
					this._NAME_P = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEX", DbType="Char(1)")]
		public System.Nullable<char> SEX
		{
			get
			{
				return this._SEX;
			}
			set
			{
				if ((this._SEX != value))
				{
					this._SEX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRDT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> BIRDT
		{
			get
			{
				return this._BIRDT;
			}
			set
			{
				if ((this._BIRDT != value))
				{
					this._BIRDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR1", DbType="VarChar(60)")]
		public string ADDR1
		{
			get
			{
				return this._ADDR1;
			}
			set
			{
				if ((this._ADDR1 != value))
				{
					this._ADDR1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR2", DbType="VarChar(60)")]
		public string ADDR2
		{
			get
			{
				return this._ADDR2;
			}
			set
			{
				if ((this._ADDR2 != value))
				{
					this._ADDR2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL1", DbType="Char(30)")]
		public string TEL1
		{
			get
			{
				return this._TEL1;
			}
			set
			{
				if ((this._TEL1 != value))
				{
					this._TEL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL2", DbType="Char(20)")]
		public string TEL2
		{
			get
			{
				return this._TEL2;
			}
			set
			{
				if ((this._TEL2 != value))
				{
					this._TEL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BBCALL", DbType="Char(15)")]
		public string BBCALL
		{
			get
			{
				return this._BBCALL;
			}
			set
			{
				if ((this._BBCALL != value))
				{
					this._BBCALL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(60)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSM", DbType="Char(15)")]
		public string GSM
		{
			get
			{
				return this._GSM;
			}
			set
			{
				if ((this._GSM != value))
				{
					this._GSM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNO", DbType="Char(10)")]
		public string IDNO
		{
			get
			{
				return this._IDNO;
			}
			set
			{
				if ((this._IDNO != value))
				{
					this._IDNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_MAN", DbType="Char(10)")]
		public string CONT_MAN
		{
			get
			{
				return this._CONT_MAN;
			}
			set
			{
				if ((this._CONT_MAN != value))
				{
					this._CONT_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_TEL", DbType="Char(20)")]
		public string CONT_TEL
		{
			get
			{
				return this._CONT_TEL;
			}
			set
			{
				if ((this._CONT_TEL != value))
				{
					this._CONT_TEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_GSM", DbType="Char(15)")]
		public string CONT_GSM
		{
			get
			{
				return this._CONT_GSM;
			}
			set
			{
				if ((this._CONT_GSM != value))
				{
					this._CONT_GSM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_MAN2", DbType="Char(10)")]
		public string CONT_MAN2
		{
			get
			{
				return this._CONT_MAN2;
			}
			set
			{
				if ((this._CONT_MAN2 != value))
				{
					this._CONT_MAN2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_TEL2", DbType="Char(20)")]
		public string CONT_TEL2
		{
			get
			{
				return this._CONT_TEL2;
			}
			set
			{
				if ((this._CONT_TEL2 != value))
				{
					this._CONT_TEL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_GSM2", DbType="Char(15)")]
		public string CONT_GSM2
		{
			get
			{
				return this._CONT_GSM2;
			}
			set
			{
				if ((this._CONT_GSM2 != value))
				{
					this._CONT_GSM2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOOD", DbType="Char(2)")]
		public string BLOOD
		{
			get
			{
				return this._BLOOD;
			}
			set
			{
				if ((this._BLOOD != value))
				{
					this._BLOOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="Char(10)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this._PASSWORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTCODE1", DbType="Char(5)")]
		public string POSTCODE1
		{
			get
			{
				return this._POSTCODE1;
			}
			set
			{
				if ((this._POSTCODE1 != value))
				{
					this._POSTCODE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTCODE2", DbType="Char(5)")]
		public string POSTCODE2
		{
			get
			{
				return this._POSTCODE2;
			}
			set
			{
				if ((this._POSTCODE2 != value))
				{
					this._POSTCODE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANK_CODE", DbType="Char(1)")]
		public System.Nullable<char> BANK_CODE
		{
			get
			{
				return this._BANK_CODE;
			}
			set
			{
				if ((this._BANK_CODE != value))
				{
					this._BANK_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKNO", DbType="Char(20)")]
		public string BANKNO
		{
			get
			{
				return this._BANKNO;
			}
			set
			{
				if ((this._BANKNO != value))
				{
					this._BANKNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_NO", DbType="Char(14)")]
		public string ACCOUNT_NO
		{
			get
			{
				return this._ACCOUNT_NO;
			}
			set
			{
				if ((this._ACCOUNT_NO != value))
				{
					this._ACCOUNT_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_NA", DbType="Char(14)")]
		public string ACCOUNT_NA
		{
			get
			{
				return this._ACCOUNT_NA;
			}
			set
			{
				if ((this._ACCOUNT_NA != value))
				{
					this._ACCOUNT_NA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARRY", DbType="Char(4)")]
		public string MARRY
		{
			get
			{
				return this._MARRY;
			}
			set
			{
				if ((this._MARRY != value))
				{
					this._MARRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="Char(15)")]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this._COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT_MA", DbType="Bit NOT NULL")]
		public bool COUNT_MA
		{
			get
			{
				return this._COUNT_MA;
			}
			set
			{
				if ((this._COUNT_MA != value))
				{
					this._COUNT_MA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARMY", DbType="Char(4)")]
		public string ARMY
		{
			get
			{
				return this._ARMY;
			}
			set
			{
				if ((this._ARMY != value))
				{
					this._ARMY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_MAN1", DbType="Char(10)")]
		public string PRO_MAN1
		{
			get
			{
				return this._PRO_MAN1;
			}
			set
			{
				if ((this._PRO_MAN1 != value))
				{
					this._PRO_MAN1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ADDR1", DbType="Char(60)")]
		public string PRO_ADDR1
		{
			get
			{
				return this._PRO_ADDR1;
			}
			set
			{
				if ((this._PRO_ADDR1 != value))
				{
					this._PRO_ADDR1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ID1", DbType="Char(10)")]
		public string PRO_ID1
		{
			get
			{
				return this._PRO_ID1;
			}
			set
			{
				if ((this._PRO_ID1 != value))
				{
					this._PRO_ID1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_TEL1", DbType="Char(20)")]
		public string PRO_TEL1
		{
			get
			{
				return this._PRO_TEL1;
			}
			set
			{
				if ((this._PRO_TEL1 != value))
				{
					this._PRO_TEL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_MAN2", DbType="Char(10)")]
		public string PRO_MAN2
		{
			get
			{
				return this._PRO_MAN2;
			}
			set
			{
				if ((this._PRO_MAN2 != value))
				{
					this._PRO_MAN2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ADDR2", DbType="Char(60)")]
		public string PRO_ADDR2
		{
			get
			{
				return this._PRO_ADDR2;
			}
			set
			{
				if ((this._PRO_ADDR2 != value))
				{
					this._PRO_ADDR2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_ID2", DbType="Char(10)")]
		public string PRO_ID2
		{
			get
			{
				return this._PRO_ID2;
			}
			set
			{
				if ((this._PRO_ID2 != value))
				{
					this._PRO_ID2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRO_TEL2", DbType="Char(20)")]
		public string PRO_TEL2
		{
			get
			{
				return this._PRO_TEL2;
			}
			set
			{
				if ((this._PRO_TEL2 != value))
				{
					this._PRO_TEL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARMY_TYPE", DbType="Char(20)")]
		public string ARMY_TYPE
		{
			get
			{
				return this._ARMY_TYPE;
			}
			set
			{
				if ((this._ARMY_TYPE != value))
				{
					this._ARMY_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N_NOBR", DbType="Char(10)")]
		public string N_NOBR
		{
			get
			{
				return this._N_NOBR;
			}
			set
			{
				if ((this._N_NOBR != value))
				{
					this._N_NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR_B", DbType="Char(10)")]
		public string NOBR_B
		{
			get
			{
				return this._NOBR_B;
			}
			set
			{
				if ((this._NOBR_B != value))
				{
					this._NOBR_B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCE", DbType="Char(20)")]
		public string PROVINCE
		{
			get
			{
				return this._PROVINCE;
			}
			set
			{
				if ((this._PROVINCE != value))
				{
					this._PROVINCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORN_ADDR", DbType="Char(20)")]
		public string BORN_ADDR
		{
			get
			{
				return this._BORN_ADDR;
			}
			set
			{
				if ((this._BORN_ADDR != value))
				{
					this._BORN_ADDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXCNT", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> TAXCNT
		{
			get
			{
				return this._TAXCNT;
			}
			set
			{
				if ((this._TAXCNT != value))
				{
					this._TAXCNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(8)")]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TYPE", DbType="Char(1)")]
		public System.Nullable<char> ID_TYPE
		{
			get
			{
				return this._ID_TYPE;
			}
			set
			{
				if ((this._ID_TYPE != value))
				{
					this._ID_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAXNO", DbType="Char(10)")]
		public string TAXNO
		{
			get
			{
				return this._TAXNO;
			}
			set
			{
				if ((this._TAXNO != value))
				{
					this._TAXNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRETAX", DbType="Decimal(5,0)")]
		public System.Nullable<decimal> PRETAX
		{
			get
			{
				return this._PRETAX;
			}
			set
			{
				if ((this._PRETAX != value))
				{
					this._PRETAX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHOTO", DbType="VarChar(200)")]
		public string PHOTO
		{
			get
			{
				return this._PHOTO;
			}
			set
			{
				if ((this._PHOTO != value))
				{
					this._PHOTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_REL1", DbType="Char(1)")]
		public System.Nullable<char> CONT_REL1
		{
			get
			{
				return this._CONT_REL1;
			}
			set
			{
				if ((this._CONT_REL1 != value))
				{
					this._CONT_REL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONT_REL2", DbType="Char(1)")]
		public System.Nullable<char> CONT_REL2
		{
			get
			{
				return this._CONT_REL2;
			}
			set
			{
				if ((this._CONT_REL2 != value))
				{
					this._CONT_REL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_MA", DbType="Char(14)")]
		public string ACCOUNT_MA
		{
			get
			{
				return this._ACCOUNT_MA;
			}
			set
			{
				if ((this._ACCOUNT_MA != value))
				{
					this._ACCOUNT_MA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATNO", DbType="Char(10)")]
		public string MATNO
		{
			get
			{
				return this._MATNO;
			}
			set
			{
				if ((this._MATNO != value))
				{
					this._MATNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBTEL", DbType="Char(5)")]
		public string SUBTEL
		{
			get
			{
				return this._SUBTEL;
			}
			set
			{
				if ((this._SUBTEL != value))
				{
					this._SUBTEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_NO", DbType="Char(40)")]
		public string LA_NO
		{
			get
			{
				return this._LA_NO;
			}
			set
			{
				if ((this._LA_NO != value))
				{
					this._LA_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_ADATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LA_ADATE
		{
			get
			{
				return this._LA_ADATE;
			}
			set
			{
				if ((this._LA_ADATE != value))
				{
					this._LA_ADATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_RECRUIT", DbType="Char(40)")]
		public string LA_RECRUIT
		{
			get
			{
				return this._LA_RECRUIT;
			}
			set
			{
				if ((this._LA_RECRUIT != value))
				{
					this._LA_RECRUIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_RECURRE", DbType="Char(20)")]
		public string LA_RECURRE
		{
			get
			{
				return this._LA_RECURRE;
			}
			set
			{
				if ((this._LA_RECURRE != value))
				{
					this._LA_RECURRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_TYPE", DbType="Char(20)")]
		public string LA_TYPE
		{
			get
			{
				return this._LA_TYPE;
			}
			set
			{
				if ((this._LA_TYPE != value))
				{
					this._LA_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_LDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LA_LDATE
		{
			get
			{
				return this._LA_LDATE;
			}
			set
			{
				if ((this._LA_LDATE != value))
				{
					this._LA_LDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_EDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LA_EDATE
		{
			get
			{
				return this._LA_EDATE;
			}
			set
			{
				if ((this._LA_EDATE != value))
				{
					this._LA_EDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_CYCLE", DbType="Bit")]
		public System.Nullable<bool> LA_CYCLE
		{
			get
			{
				return this._LA_CYCLE;
			}
			set
			{
				if ((this._LA_CYCLE != value))
				{
					this._LA_CYCLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_NOTE", DbType="Char(200)")]
		public string LA_NOTE
		{
			get
			{
				return this._LA_NOTE;
			}
			set
			{
				if ((this._LA_NOTE != value))
				{
					this._LA_NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_AMT", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> LA_AMT
		{
			get
			{
				return this._LA_AMT;
			}
			set
			{
				if ((this._LA_AMT != value))
				{
					this._LA_AMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LA_OUTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LA_OUTDATE
		{
			get
			{
				return this._LA_OUTDATE;
			}
			set
			{
				if ((this._LA_OUTDATE != value))
				{
					this._LA_OUTDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiveYears", DbType="Char(4)")]
		public string FiveYears
		{
			get
			{
				return this._FiveYears;
			}
			set
			{
				if ((this._FiveYears != value))
				{
					this._FiveYears = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiveRecipient", DbType="Char(4)")]
		public string FiveRecipient
		{
			get
			{
				return this._FiveRecipient;
			}
			set
			{
				if ((this._FiveRecipient != value))
				{
					this._FiveRecipient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenYears", DbType="Char(4)")]
		public string TenYears
		{
			get
			{
				return this._TenYears;
			}
			set
			{
				if ((this._TenYears != value))
				{
					this._TenYears = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenRecipient", DbType="Char(4)")]
		public string TenRecipient
		{
			get
			{
				return this._TenRecipient;
			}
			set
			{
				if ((this._TenRecipient != value))
				{
					this._TenRecipient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FifteenYears", DbType="Char(4)")]
		public string FifteenYears
		{
			get
			{
				return this._FifteenYears;
			}
			set
			{
				if ((this._FifteenYears != value))
				{
					this._FifteenYears = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiteenRecipient", DbType="Char(4)")]
		public string FiteenRecipient
		{
			get
			{
				return this._FiteenRecipient;
			}
			set
			{
				if ((this._FiteenRecipient != value))
				{
					this._FiteenRecipient = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BASETTS")]
	public partial class BASETTS
	{
		
		private string _NOBR;
		
		private System.Nullable<char> _TTSCODE;
		
		private System.Nullable<System.DateTime> _ADATE;
		
		private System.Nullable<System.DateTime> _DDATE;
		
		private System.Nullable<System.DateTime> _INDT;
		
		private System.Nullable<System.DateTime> _CINDT;
		
		private System.Nullable<System.DateTime> _OUDT;
		
		private System.Nullable<System.DateTime> _STDT;
		
		private System.Nullable<System.DateTime> _STINDT;
		
		private System.Nullable<System.DateTime> _STOUDT;
		
		private string _COMP;
		
		private string _DEPT;
		
		private string _DEPTS;
		
		private string _JOB;
		
		private string _JOBL;
		
		private System.Nullable<char> _CARD;
		
		private string _ROTET;
		
		private System.Nullable<char> _DI;
		
		private string _KEY_MAN;
		
		private System.Nullable<System.DateTime> _KEY_DATE;
		
		private System.Nullable<bool> _MANG;
		
		private System.Nullable<decimal> _YR_DAYS;
		
		private System.Nullable<decimal> _WK_YRS;
		
		private string _SALTP;
		
		private string _JOBS;
		
		private string _WORKCD;
		
		private string _CARCD;
		
		private System.Nullable<char> _EMPCD;
		
		private string _OUTCD;
		
		private string _OUTCD1;
		
		private System.Nullable<bool> _CALABS;
		
		private System.Nullable<char> _CALOT;
		
		private System.Nullable<bool> _FULATT;
		
		private System.Nullable<bool> _NOTER;
		
		private System.Nullable<bool> _NOWEL;
		
		private System.Nullable<bool> _NORET;
		
		private System.Nullable<bool> _NOTLATE;
		
		private System.Nullable<char> _HOLI_CODE;
		
		private System.Nullable<bool> _NOOT;
		
		private System.Nullable<bool> _NOSPEC;
		
		private System.Nullable<bool> _NOCARD;
		
		private System.Nullable<bool> _NOEAT;
		
		private string _APGRPCD;
		
		private string _DEPTM;
		
		private string _TTSCD;
		
		private string _MENO;
		
		private string _SALADR;
		
		private System.Nullable<bool> _NOWAGE;
		
		private System.Nullable<bool> _MANGE;
		
		private System.Nullable<double> _RETRATE;
		
		private System.Nullable<System.DateTime> _RETDATE;
		
		private System.Nullable<char> _RETCHOO;
		
		private System.Nullable<System.DateTime> _RETDATE1;
		
		private System.Nullable<bool> _ONLYONTIME;
		
		private string _JOBO;
		
		private System.Nullable<bool> _COUNT_PASS;
		
		private System.Nullable<System.DateTime> _PASS_DATE;
		
		private System.Nullable<bool> _MANG1;
		
		private System.Nullable<System.DateTime> _AP_DATE;
		
		private System.Nullable<decimal> _GRP_AMT;
		
		private System.Nullable<System.DateTime> _TAX_DATE;
		
		private System.Nullable<bool> _NOSPAMT;
		
		private System.Nullable<bool> _FIXRATE;
		
		private System.Nullable<System.DateTime> _TAX_EDATE;
		
		private string _SUP_NOBR;
		
		private string _AGE_NOBR;
		
		private System.Nullable<bool> _NODormitory;
		
		public BASETTS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="Char(10)")]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this._NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTSCODE", DbType="Char(1)")]
		public System.Nullable<char> TTSCODE
		{
			get
			{
				return this._TTSCODE;
			}
			set
			{
				if ((this._TTSCODE != value))
				{
					this._TTSCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ADATE
		{
			get
			{
				return this._ADATE;
			}
			set
			{
				if ((this._ADATE != value))
				{
					this._ADATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DDATE
		{
			get
			{
				return this._DDATE;
			}
			set
			{
				if ((this._DDATE != value))
				{
					this._DDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> INDT
		{
			get
			{
				return this._INDT;
			}
			set
			{
				if ((this._INDT != value))
				{
					this._INDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CINDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CINDT
		{
			get
			{
				return this._CINDT;
			}
			set
			{
				if ((this._CINDT != value))
				{
					this._CINDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> OUDT
		{
			get
			{
				return this._OUDT;
			}
			set
			{
				if ((this._OUDT != value))
				{
					this._OUDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> STDT
		{
			get
			{
				return this._STDT;
			}
			set
			{
				if ((this._STDT != value))
				{
					this._STDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STINDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> STINDT
		{
			get
			{
				return this._STINDT;
			}
			set
			{
				if ((this._STINDT != value))
				{
					this._STINDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOUDT", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOUDT
		{
			get
			{
				return this._STOUDT;
			}
			set
			{
				if ((this._STOUDT != value))
				{
					this._STOUDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMP", DbType="Char(4)")]
		public string COMP
		{
			get
			{
				return this._COMP;
			}
			set
			{
				if ((this._COMP != value))
				{
					this._COMP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="Char(10)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPTS", DbType="Char(10)")]
		public string DEPTS
		{
			get
			{
				return this._DEPTS;
			}
			set
			{
				if ((this._DEPTS != value))
				{
					this._DEPTS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB", DbType="Char(6)")]
		public string JOB
		{
			get
			{
				return this._JOB;
			}
			set
			{
				if ((this._JOB != value))
				{
					this._JOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBL", DbType="Char(4)")]
		public string JOBL
		{
			get
			{
				return this._JOBL;
			}
			set
			{
				if ((this._JOBL != value))
				{
					this._JOBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARD", DbType="Char(1)")]
		public System.Nullable<char> CARD
		{
			get
			{
				return this._CARD;
			}
			set
			{
				if ((this._CARD != value))
				{
					this._CARD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROTET", DbType="Char(2)")]
		public string ROTET
		{
			get
			{
				return this._ROTET;
			}
			set
			{
				if ((this._ROTET != value))
				{
					this._ROTET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DI", DbType="Char(1)")]
		public System.Nullable<char> DI
		{
			get
			{
				return this._DI;
			}
			set
			{
				if ((this._DI != value))
				{
					this._DI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(8)")]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANG", DbType="Bit")]
		public System.Nullable<bool> MANG
		{
			get
			{
				return this._MANG;
			}
			set
			{
				if ((this._MANG != value))
				{
					this._MANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YR_DAYS", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> YR_DAYS
		{
			get
			{
				return this._YR_DAYS;
			}
			set
			{
				if ((this._YR_DAYS != value))
				{
					this._YR_DAYS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WK_YRS", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> WK_YRS
		{
			get
			{
				return this._WK_YRS;
			}
			set
			{
				if ((this._WK_YRS != value))
				{
					this._WK_YRS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALTP", DbType="Char(2)")]
		public string SALTP
		{
			get
			{
				return this._SALTP;
			}
			set
			{
				if ((this._SALTP != value))
				{
					this._SALTP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBS", DbType="Char(3)")]
		public string JOBS
		{
			get
			{
				return this._JOBS;
			}
			set
			{
				if ((this._JOBS != value))
				{
					this._JOBS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKCD", DbType="Char(2)")]
		public string WORKCD
		{
			get
			{
				return this._WORKCD;
			}
			set
			{
				if ((this._WORKCD != value))
				{
					this._WORKCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARCD", DbType="Char(3)")]
		public string CARCD
		{
			get
			{
				return this._CARCD;
			}
			set
			{
				if ((this._CARCD != value))
				{
					this._CARCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPCD", DbType="Char(1)")]
		public System.Nullable<char> EMPCD
		{
			get
			{
				return this._EMPCD;
			}
			set
			{
				if ((this._EMPCD != value))
				{
					this._EMPCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUTCD", DbType="Char(2)")]
		public string OUTCD
		{
			get
			{
				return this._OUTCD;
			}
			set
			{
				if ((this._OUTCD != value))
				{
					this._OUTCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUTCD1", DbType="Char(3)")]
		public string OUTCD1
		{
			get
			{
				return this._OUTCD1;
			}
			set
			{
				if ((this._OUTCD1 != value))
				{
					this._OUTCD1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALABS", DbType="Bit")]
		public System.Nullable<bool> CALABS
		{
			get
			{
				return this._CALABS;
			}
			set
			{
				if ((this._CALABS != value))
				{
					this._CALABS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALOT", DbType="Char(1)")]
		public System.Nullable<char> CALOT
		{
			get
			{
				return this._CALOT;
			}
			set
			{
				if ((this._CALOT != value))
				{
					this._CALOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULATT", DbType="Bit")]
		public System.Nullable<bool> FULATT
		{
			get
			{
				return this._FULATT;
			}
			set
			{
				if ((this._FULATT != value))
				{
					this._FULATT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTER", DbType="Bit")]
		public System.Nullable<bool> NOTER
		{
			get
			{
				return this._NOTER;
			}
			set
			{
				if ((this._NOTER != value))
				{
					this._NOTER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOWEL", DbType="Bit")]
		public System.Nullable<bool> NOWEL
		{
			get
			{
				return this._NOWEL;
			}
			set
			{
				if ((this._NOWEL != value))
				{
					this._NOWEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NORET", DbType="Bit")]
		public System.Nullable<bool> NORET
		{
			get
			{
				return this._NORET;
			}
			set
			{
				if ((this._NORET != value))
				{
					this._NORET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTLATE", DbType="Bit")]
		public System.Nullable<bool> NOTLATE
		{
			get
			{
				return this._NOTLATE;
			}
			set
			{
				if ((this._NOTLATE != value))
				{
					this._NOTLATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOLI_CODE", DbType="Char(1)")]
		public System.Nullable<char> HOLI_CODE
		{
			get
			{
				return this._HOLI_CODE;
			}
			set
			{
				if ((this._HOLI_CODE != value))
				{
					this._HOLI_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOOT", DbType="Bit")]
		public System.Nullable<bool> NOOT
		{
			get
			{
				return this._NOOT;
			}
			set
			{
				if ((this._NOOT != value))
				{
					this._NOOT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSPEC", DbType="Bit")]
		public System.Nullable<bool> NOSPEC
		{
			get
			{
				return this._NOSPEC;
			}
			set
			{
				if ((this._NOSPEC != value))
				{
					this._NOSPEC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOCARD", DbType="Bit")]
		public System.Nullable<bool> NOCARD
		{
			get
			{
				return this._NOCARD;
			}
			set
			{
				if ((this._NOCARD != value))
				{
					this._NOCARD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOEAT", DbType="Bit")]
		public System.Nullable<bool> NOEAT
		{
			get
			{
				return this._NOEAT;
			}
			set
			{
				if ((this._NOEAT != value))
				{
					this._NOEAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APGRPCD", DbType="Char(5)")]
		public string APGRPCD
		{
			get
			{
				return this._APGRPCD;
			}
			set
			{
				if ((this._APGRPCD != value))
				{
					this._APGRPCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPTM", DbType="Char(10)")]
		public string DEPTM
		{
			get
			{
				return this._DEPTM;
			}
			set
			{
				if ((this._DEPTM != value))
				{
					this._DEPTM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTSCD", DbType="Char(2)")]
		public string TTSCD
		{
			get
			{
				return this._TTSCD;
			}
			set
			{
				if ((this._TTSCD != value))
				{
					this._TTSCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENO", DbType="Char(180)")]
		public string MENO
		{
			get
			{
				return this._MENO;
			}
			set
			{
				if ((this._MENO != value))
				{
					this._MENO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALADR", DbType="Char(2)")]
		public string SALADR
		{
			get
			{
				return this._SALADR;
			}
			set
			{
				if ((this._SALADR != value))
				{
					this._SALADR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOWAGE", DbType="Bit")]
		public System.Nullable<bool> NOWAGE
		{
			get
			{
				return this._NOWAGE;
			}
			set
			{
				if ((this._NOWAGE != value))
				{
					this._NOWAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGE", DbType="Bit")]
		public System.Nullable<bool> MANGE
		{
			get
			{
				return this._MANGE;
			}
			set
			{
				if ((this._MANGE != value))
				{
					this._MANGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETRATE", DbType="Float")]
		public System.Nullable<double> RETRATE
		{
			get
			{
				return this._RETRATE;
			}
			set
			{
				if ((this._RETRATE != value))
				{
					this._RETRATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> RETDATE
		{
			get
			{
				return this._RETDATE;
			}
			set
			{
				if ((this._RETDATE != value))
				{
					this._RETDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETCHOO", DbType="Char(1)")]
		public System.Nullable<char> RETCHOO
		{
			get
			{
				return this._RETCHOO;
			}
			set
			{
				if ((this._RETCHOO != value))
				{
					this._RETCHOO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETDATE1", DbType="DateTime")]
		public System.Nullable<System.DateTime> RETDATE1
		{
			get
			{
				return this._RETDATE1;
			}
			set
			{
				if ((this._RETDATE1 != value))
				{
					this._RETDATE1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ONLYONTIME", DbType="Bit")]
		public System.Nullable<bool> ONLYONTIME
		{
			get
			{
				return this._ONLYONTIME;
			}
			set
			{
				if ((this._ONLYONTIME != value))
				{
					this._ONLYONTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBO", DbType="Char(6)")]
		public string JOBO
		{
			get
			{
				return this._JOBO;
			}
			set
			{
				if ((this._JOBO != value))
				{
					this._JOBO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT_PASS", DbType="Bit")]
		public System.Nullable<bool> COUNT_PASS
		{
			get
			{
				return this._COUNT_PASS;
			}
			set
			{
				if ((this._COUNT_PASS != value))
				{
					this._COUNT_PASS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> PASS_DATE
		{
			get
			{
				return this._PASS_DATE;
			}
			set
			{
				if ((this._PASS_DATE != value))
				{
					this._PASS_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANG1", DbType="Bit")]
		public System.Nullable<bool> MANG1
		{
			get
			{
				return this._MANG1;
			}
			set
			{
				if ((this._MANG1 != value))
				{
					this._MANG1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AP_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> AP_DATE
		{
			get
			{
				return this._AP_DATE;
			}
			set
			{
				if ((this._AP_DATE != value))
				{
					this._AP_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRP_AMT", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> GRP_AMT
		{
			get
			{
				return this._GRP_AMT;
			}
			set
			{
				if ((this._GRP_AMT != value))
				{
					this._GRP_AMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TAX_DATE
		{
			get
			{
				return this._TAX_DATE;
			}
			set
			{
				if ((this._TAX_DATE != value))
				{
					this._TAX_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOSPAMT", DbType="Bit")]
		public System.Nullable<bool> NOSPAMT
		{
			get
			{
				return this._NOSPAMT;
			}
			set
			{
				if ((this._NOSPAMT != value))
				{
					this._NOSPAMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIXRATE", DbType="Bit")]
		public System.Nullable<bool> FIXRATE
		{
			get
			{
				return this._FIXRATE;
			}
			set
			{
				if ((this._FIXRATE != value))
				{
					this._FIXRATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAX_EDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> TAX_EDATE
		{
			get
			{
				return this._TAX_EDATE;
			}
			set
			{
				if ((this._TAX_EDATE != value))
				{
					this._TAX_EDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUP_NOBR", DbType="Char(10)")]
		public string SUP_NOBR
		{
			get
			{
				return this._SUP_NOBR;
			}
			set
			{
				if ((this._SUP_NOBR != value))
				{
					this._SUP_NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE_NOBR", DbType="Char(10)")]
		public string AGE_NOBR
		{
			get
			{
				return this._AGE_NOBR;
			}
			set
			{
				if ((this._AGE_NOBR != value))
				{
					this._AGE_NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NODormitory", DbType="Bit")]
		public System.Nullable<bool> NODormitory
		{
			get
			{
				return this._NODormitory;
			}
			set
			{
				if ((this._NODormitory != value))
				{
					this._NODormitory = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPTA")]
	public partial class DEPTA
	{
		
		private string _D_NO;
		
		private string _D_NAME;
		
		private System.Nullable<System.DateTime> _KEY_DATE;
		
		private string _KEY_MAN;
		
		private string _OLD_DEPT;
		
		private string _DEPT_GROUP;
		
		private string _DEPT_TREE;
		
		private string _DEPT_CATE;
		
		private System.Nullable<System.DateTime> _ADATE;
		
		private System.Nullable<System.DateTime> _DDATE;
		
		private string _ABSEMAIL;
		
		private string _MENO;
		
		public DEPTA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NO", DbType="Char(10)")]
		public string D_NO
		{
			get
			{
				return this._D_NO;
			}
			set
			{
				if ((this._D_NO != value))
				{
					this._D_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NAME", DbType="Char(24)")]
		public string D_NAME
		{
			get
			{
				return this._D_NAME;
			}
			set
			{
				if ((this._D_NAME != value))
				{
					this._D_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(8)")]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_DEPT", DbType="Char(10)")]
		public string OLD_DEPT
		{
			get
			{
				return this._OLD_DEPT;
			}
			set
			{
				if ((this._OLD_DEPT != value))
				{
					this._OLD_DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_GROUP", DbType="Char(10)")]
		public string DEPT_GROUP
		{
			get
			{
				return this._DEPT_GROUP;
			}
			set
			{
				if ((this._DEPT_GROUP != value))
				{
					this._DEPT_GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_TREE", DbType="Char(10)")]
		public string DEPT_TREE
		{
			get
			{
				return this._DEPT_TREE;
			}
			set
			{
				if ((this._DEPT_TREE != value))
				{
					this._DEPT_TREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CATE", DbType="NVarChar(10)")]
		public string DEPT_CATE
		{
			get
			{
				return this._DEPT_CATE;
			}
			set
			{
				if ((this._DEPT_CATE != value))
				{
					this._DEPT_CATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ADATE
		{
			get
			{
				return this._ADATE;
			}
			set
			{
				if ((this._ADATE != value))
				{
					this._ADATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DDATE
		{
			get
			{
				return this._DDATE;
			}
			set
			{
				if ((this._DDATE != value))
				{
					this._DDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABSEMAIL", DbType="Char(200)")]
		public string ABSEMAIL
		{
			get
			{
				return this._ABSEMAIL;
			}
			set
			{
				if ((this._ABSEMAIL != value))
				{
					this._ABSEMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENO", DbType="Char(200)")]
		public string MENO
		{
			get
			{
				return this._MENO;
			}
			set
			{
				if ((this._MENO != value))
				{
					this._MENO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DEPT")]
	public partial class DEPT
	{
		
		private string _D_NO;
		
		private string _D_NAME;
		
		private System.Nullable<double> _PNS;
		
		private string _DEPT_TREE;
		
		private System.Nullable<System.DateTime> _KEY_DATE;
		
		private string _KEY_MAN;
		
		private string _OLD_DEPT;
		
		private string _NEW_DEPT;
		
		private System.Nullable<System.DateTime> _ADATE;
		
		private System.Nullable<System.DateTime> _DDATE;
		
		private string _DEPT_GROUP;
		
		private string _DEPT_CATE;
		
		private string _DeptBudgetGroup;
		
		private string _BudgetEMAIL;
		
		private string _MENO;
		
		public DEPT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NO", DbType="Char(10)")]
		public string D_NO
		{
			get
			{
				return this._D_NO;
			}
			set
			{
				if ((this._D_NO != value))
				{
					this._D_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_NAME", DbType="Char(40)")]
		public string D_NAME
		{
			get
			{
				return this._D_NAME;
			}
			set
			{
				if ((this._D_NAME != value))
				{
					this._D_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNS", DbType="Float")]
		public System.Nullable<double> PNS
		{
			get
			{
				return this._PNS;
			}
			set
			{
				if ((this._PNS != value))
				{
					this._PNS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_TREE", DbType="Char(10)")]
		public string DEPT_TREE
		{
			get
			{
				return this._DEPT_TREE;
			}
			set
			{
				if ((this._DEPT_TREE != value))
				{
					this._DEPT_TREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(8)")]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_DEPT", DbType="Char(10)")]
		public string OLD_DEPT
		{
			get
			{
				return this._OLD_DEPT;
			}
			set
			{
				if ((this._OLD_DEPT != value))
				{
					this._OLD_DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NEW_DEPT", DbType="Char(10)")]
		public string NEW_DEPT
		{
			get
			{
				return this._NEW_DEPT;
			}
			set
			{
				if ((this._NEW_DEPT != value))
				{
					this._NEW_DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ADATE
		{
			get
			{
				return this._ADATE;
			}
			set
			{
				if ((this._ADATE != value))
				{
					this._ADATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DDATE
		{
			get
			{
				return this._DDATE;
			}
			set
			{
				if ((this._DDATE != value))
				{
					this._DDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_GROUP", DbType="Char(10)")]
		public string DEPT_GROUP
		{
			get
			{
				return this._DEPT_GROUP;
			}
			set
			{
				if ((this._DEPT_GROUP != value))
				{
					this._DEPT_GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CATE", DbType="NVarChar(10)")]
		public string DEPT_CATE
		{
			get
			{
				return this._DEPT_CATE;
			}
			set
			{
				if ((this._DEPT_CATE != value))
				{
					this._DEPT_CATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptBudgetGroup", DbType="Char(10)")]
		public string DeptBudgetGroup
		{
			get
			{
				return this._DeptBudgetGroup;
			}
			set
			{
				if ((this._DeptBudgetGroup != value))
				{
					this._DeptBudgetGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetEMAIL", DbType="Char(200)")]
		public string BudgetEMAIL
		{
			get
			{
				return this._BudgetEMAIL;
			}
			set
			{
				if ((this._BudgetEMAIL != value))
				{
					this._BudgetEMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENO", DbType="Char(200)")]
		public string MENO
		{
			get
			{
				return this._MENO;
			}
			set
			{
				if ((this._MENO != value))
				{
					this._MENO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JOB")]
	public partial class JOB
	{
		
		private string _JOB1;
		
		private string _JOB_NAME;
		
		private System.Nullable<System.DateTime> _KEY_DATE;
		
		private string _KEY_MAN;
		
		private System.Nullable<char> _JOB_TREE;
		
		private string _JOBL;
		
		private string _JOBLB;
		
		private string _JOBLE;
		
		private string _OLD_JOB;
		
		private System.Nullable<bool> _WORKAMT;
		
		public JOB()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="JOB", Storage="_JOB1", DbType="Char(6)")]
		public string JOB1
		{
			get
			{
				return this._JOB1;
			}
			set
			{
				if ((this._JOB1 != value))
				{
					this._JOB1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_NAME", DbType="Char(16)")]
		public string JOB_NAME
		{
			get
			{
				return this._JOB_NAME;
			}
			set
			{
				if ((this._JOB_NAME != value))
				{
					this._JOB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(8)")]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_TREE", DbType="Char(1)")]
		public System.Nullable<char> JOB_TREE
		{
			get
			{
				return this._JOB_TREE;
			}
			set
			{
				if ((this._JOB_TREE != value))
				{
					this._JOB_TREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBL", DbType="Char(4)")]
		public string JOBL
		{
			get
			{
				return this._JOBL;
			}
			set
			{
				if ((this._JOBL != value))
				{
					this._JOBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBLB", DbType="Char(4)")]
		public string JOBLB
		{
			get
			{
				return this._JOBLB;
			}
			set
			{
				if ((this._JOBLB != value))
				{
					this._JOBLB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBLE", DbType="Char(4)")]
		public string JOBLE
		{
			get
			{
				return this._JOBLE;
			}
			set
			{
				if ((this._JOBLE != value))
				{
					this._JOBLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_JOB", DbType="Char(6)")]
		public string OLD_JOB
		{
			get
			{
				return this._OLD_JOB;
			}
			set
			{
				if ((this._OLD_JOB != value))
				{
					this._OLD_JOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKAMT", DbType="Bit")]
		public System.Nullable<bool> WORKAMT
		{
			get
			{
				return this._WORKAMT;
			}
			set
			{
				if ((this._WORKAMT != value))
				{
					this._WORKAMT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
