#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EFASTHR")]
public partial class dcHRDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  #endregion
	
	public dcHRDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JBHR.Dll.Properties.Settings.JBHRConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dcHRDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcHRDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcHRDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dcHRDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<FORMCD> FORMCD
	{
		get
		{
			return this.GetTable<FORMCD>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FORMCD")]
public partial class FORMCD
{
	
	private string _sCode;
	
	private string _sName;
	
	private System.DateTime _dKeyDate;
	
	private string _sKeyName;
	
	public FORMCD()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FORMCD", Storage="_sCode", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string sCode
	{
		get
		{
			return this._sCode;
		}
		set
		{
			if ((this._sCode != value))
			{
				this._sCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="FRM_NAME", Storage="_sName", DbType="Char(12) NOT NULL", CanBeNull=false)]
	public string sName
	{
		get
		{
			return this._sName;
		}
		set
		{
			if ((this._sName != value))
			{
				this._sName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KEY_DATE", Storage="_dKeyDate", DbType="DateTime NOT NULL")]
	public System.DateTime dKeyDate
	{
		get
		{
			return this._dKeyDate;
		}
		set
		{
			if ((this._dKeyDate != value))
			{
				this._dKeyDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KEY_MAN", Storage="_sKeyName", DbType="Char(8) NOT NULL", CanBeNull=false)]
	public string sKeyName
	{
		get
		{
			return this._sKeyName;
		}
		set
		{
			if ((this._sKeyName != value))
			{
				this._sKeyName = value;
			}
		}
	}
}
#pragma warning restore 1591
