#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowAutoSave
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="waferhr")]
	public partial class dcHrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    #endregion
		
		public dcHrDataContext() : 
				base(global::FlowAutoSave.Properties.Settings.Default.waferhrConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcHrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABS> ABS
		{
			get
			{
				return this.GetTable<ABS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABS")]
	public partial class ABS
	{
		
		private string _NOBR;
		
		private System.Nullable<System.DateTime> _BDATE;
		
		private System.Nullable<System.DateTime> _EDATE;
		
		private string _BTIME;
		
		private string _ETIME;
		
		private string _H_CODE;
		
		private System.Nullable<decimal> _TOL_HOURS;
		
		private string _KEY_MAN;
		
		private System.Nullable<System.DateTime> _KEY_DATE;
		
		private string _YYMM;
		
		private bool _NOTEDIT;
		
		private string _NOTE;
		
		private bool _SYSCREATE;
		
		private System.Nullable<decimal> _TOL_DAY;
		
		private string _A_NAME;
		
		private string _SERNO;
		
		private System.Nullable<bool> _RSYSCREATE;
		
		public ABS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOBR", DbType="Char(10)")]
		public string NOBR
		{
			get
			{
				return this._NOBR;
			}
			set
			{
				if ((this._NOBR != value))
				{
					this._NOBR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> BDATE
		{
			get
			{
				return this._BDATE;
			}
			set
			{
				if ((this._BDATE != value))
				{
					this._BDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> EDATE
		{
			get
			{
				return this._EDATE;
			}
			set
			{
				if ((this._EDATE != value))
				{
					this._EDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTIME", DbType="Char(4)")]
		public string BTIME
		{
			get
			{
				return this._BTIME;
			}
			set
			{
				if ((this._BTIME != value))
				{
					this._BTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETIME", DbType="Char(4)")]
		public string ETIME
		{
			get
			{
				return this._ETIME;
			}
			set
			{
				if ((this._ETIME != value))
				{
					this._ETIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H_CODE", DbType="Char(2)")]
		public string H_CODE
		{
			get
			{
				return this._H_CODE;
			}
			set
			{
				if ((this._H_CODE != value))
				{
					this._H_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOL_HOURS", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> TOL_HOURS
		{
			get
			{
				return this._TOL_HOURS;
			}
			set
			{
				if ((this._TOL_HOURS != value))
				{
					this._TOL_HOURS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="Char(20)")]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this._KEY_MAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this._KEY_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYMM", DbType="Char(5)")]
		public string YYMM
		{
			get
			{
				return this._YYMM;
			}
			set
			{
				if ((this._YYMM != value))
				{
					this._YYMM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTEDIT", DbType="Bit NOT NULL")]
		public bool NOTEDIT
		{
			get
			{
				return this._NOTEDIT;
			}
			set
			{
				if ((this._NOTEDIT != value))
				{
					this._NOTEDIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(200)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this._NOTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSCREATE", DbType="Bit NOT NULL")]
		public bool SYSCREATE
		{
			get
			{
				return this._SYSCREATE;
			}
			set
			{
				if ((this._SYSCREATE != value))
				{
					this._SYSCREATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOL_DAY", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TOL_DAY
		{
			get
			{
				return this._TOL_DAY;
			}
			set
			{
				if ((this._TOL_DAY != value))
				{
					this._TOL_DAY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A_NAME", DbType="Char(10)")]
		public string A_NAME
		{
			get
			{
				return this._A_NAME;
			}
			set
			{
				if ((this._A_NAME != value))
				{
					this._A_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERNO", DbType="VarChar(50)")]
		public string SERNO
		{
			get
			{
				return this._SERNO;
			}
			set
			{
				if ((this._SERNO != value))
				{
					this._SERNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSYSCREATE", DbType="Bit")]
		public System.Nullable<bool> RSYSCREATE
		{
			get
			{
				return this._RSYSCREATE;
			}
			set
			{
				if ((this._RSYSCREATE != value))
				{
					this._RSYSCREATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
